version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alarma_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - db_data:/usr/src/app/data
    environment:
      PORT: 3000
      DB_PATH: /usr/src/app/alarma.db
      NODE_ENV: development
    command: npm run dev

volumes:
  db_data:
